services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app # Mounts your repo into the container
