version: '3'
services:
  postgres_db:
    image: postgis/postgis:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - "5432"
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres_db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped
    links:
      - "postgres_db:pgsql-server"

  python:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped
    command: tail -f /dev/null
    depends_on:
      - postgres_db
    stdin_open: true
    tty: true
    environment:
      HISTFILE: /python/.bash_history
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    volumes:
      - $HOME/mapwizard/interpolation-methods/:/usr/src/app/:Z
      - $HOME/mapwizard/data/:/usr/src/app/data/:Z
      - $HOME/.docker_bash_history:/root/.bash_history
    network_mode: host

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
